### ISSUE TITLE
sudo not working

### ISSUE THREAD

**Issue by changemenemo** [chenjr0719/Docker-Ubuntu-MATE-noVNC#1]
Could you do some testing about your sudo part in your startup.sh ? 
because sudo is well put at yes in my environment var
and still it tells me that ubuntu is not in the sudoers file. and when I ask for the groups of ubuntu, it don't give me the sudo group...

**Comment by changemenemo** [comment]
find the problem. Don't forget to put your password between '....' to not screw the rest of the line.

**Comment by chenjr0719** [comment]
Sorry about the late reply and thanks for you to point out this problem.
I finish some testing about sudo part.
I found that [if condition](https://github.com/chenjr0719/Docker-Ubuntu-MATE-noVNC/blob/master/startup.sh#L16) of sudo may cause something wrong.
At least when I remove the part after && can make it work properly.
However, I still need some method to determine the input environment is yes or something like.
So, I will fix this problem tomorrow and find a better way to complete this if statement.
If you still have any idea or suggestion about this image, feel free to propose.

Thanks
Jacob

**Comment by chenjr0719** [comment]
Fix at  [f8257d8](https://github.com/chenjr0719/Docker-Ubuntu-MATE-noVNC/commit/f8257d8a0e8cf114997a0e0775047daf992155f3).
